closes #53 readme process
pharmaverse/admiral.test pull request #55
Opened 2022-06-10 13:40 UTC by rossfarrugia

@bundfussr @bms63 @thomas-neitmann - clarified the process of how we update the test data in the README file, as we're going to have more package extension teams needing to do this, e.g. vaccine datasets will need to be added. So that we have something to point them towards and the process remains consistent. Appreciate if you can all take a look and check if i haven't missed or misunderstood anything.

2022-06-10 13:53 UTC, bundfussr approved these changes

2022-06-10 15:52 UTC, bms63 commented on README.md
> +## Adding New
```suggestion
## Adding New SDTM Datasets
```

2022-06-10 15:53 UTC, bms63 requested changes
Looking good just a few suggestions

2022-06-12 16:52 UTC, bms63 approved these changes
Looks good!

2022-06-12 16:52 UTC, merged